# Generated by Django 4.1.5 on 2023-01-21 10:30

from django.db import migrations


def add_age_values(apps, schema_editor):
    age_values_model = apps.get_model('myapp', 'AgeValues')
    age_values = [
        {'start_age': 14, 'end_age': 17, 'value': 0.5},
        {'start_age': 18, 'end_age': 23, 'value': 1},
        {'start_age': 24, 'end_age': 30, 'value': 0.8},
        # ...
    ]
    for age_value in age_values:
        age_values_model.objects.create(**age_value)


def delete_age_values(apps, schema_editor):
    age_values = apps.get_model('myapp', 'AgeValues')
    age_values.objects.all().delete()


def add_weight_values(apps, schema_editor):
    weight_values_model = apps.get_model('myapp', 'WeightValues')
    weight_values = [
        {'start_weight': 45, 'end_weight': 50, 'value': 1.2},
        {'start_weight': 51, 'end_weight': 55, 'value': 1},
        {'start_weight': 56, 'end_weight': 60, 'value': 0.8},
        # ...
    ]
    for weight_value in weight_values:
        weight_values_model.objects.create(**weight_value)


def delete_weight_values(apps, schema_editor):
    weight_values = apps.get_model('myapp', 'WeightValues')
    weight_values.objects.all().delete()


def add_education_values(apps, schema_editor):
    education_values_model = apps.get_model('myapp', 'EducationValues')
    education_values = [
        {'education': "Доктор", 'value': 1.6},
        {'education': "Магистр", 'value': 1.4},
        {'education': "Бакалавр", 'value': 1.2},
        {'education': "Колледж", 'value': 1},
        {'education': "Старшая школа", 'value': 0.8},
        {'education': "Средняя школа", 'value': 0.5},
        {'education': "Нет", 'value': 0.2},
        {'education': "Садик", 'value': 0},
        # ...
    ]
    for education_value in education_values:
        education_values_model.objects.create(**education_value)


def delete_education_values(apps, schema_editor):
    education_values = apps.get_model('myapp', 'EducationValues')
    education_values.objects.all().delete()


def add_place_values(apps, schema_editor):
    place_values_model = apps.get_model('myapp', 'PlaceValues')
    place_values = [
        {'place': "Чуй", 'value': 100000},
        {'place': "Нарын", 'value': 90000},
        {'place': "Ош", 'value': 80000},
        {'place': "Ыссык куль", 'value': 60000},
        {'place': "Талас", 'value': 175000},
        {'place': "Жалал Абад", 'value': 75000},
        {'place': "Баткен", 'value': 70000},
        # ...
    ]
    for place_value in place_values:
        place_values_model.objects.create(**place_value)


def delete_place_values(apps, schema_editor):
    place_values = apps.get_model('myapp', 'PlaceValues')
    place_values.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_age_values),
        migrations.RunPython(delete_weight_values),
        migrations.RunPython(delete_place_values),
        migrations.RunPython(delete_education_values),
        migrations.RunPython(add_age_values),
        migrations.RunPython(add_weight_values),
        migrations.RunPython(add_education_values),
        migrations.RunPython(add_place_values),
    ]
